// Copyright {{_date_}} {{_author_}}. All rights reserved
// Use of this source code is generated by a BSD-style
// license that can be found in the LICENSE file

package {{_file_name_}}

func main() {
	{{_cursor_}}
}
