set -g @plugin 'obergodmar/kanagawa-tmux'

# set -g @kanagawa_status-right "#[fg=default]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml) #[fg=default,bg=default]%d %b #[fg=default,bg=default]%H:%M #{pomodoro_status}"

# vim: set filetype=tmux :
