# rose-pine
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'moon'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'
# set -g @rose_pine_status_right_prepend_section "#[fg=white,nobold]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml) #[fg=yellow,bg=default]%d %b #[fg=white,bg=default]%H:%M "
set -g @rose_pine_status_right_prepend_section "#[fg=default]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml) #[fg=default,bg=default]%d %b #[fg=default,bg=default]%H:%M "
set -g @rose_pine_directory 'off'
# These are not padded
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
# set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
# set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
# set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname
# set -g @rose_pine_date_time_icon '󰃰' # Changes the default icon to the right of the date module

# vim: set filetype=tmux :
