local g = vim.g
g.markdown_enable_conceal=true
g.markdown_enable_insert_mode_mappings = false
g.user_emmet_leader_key = "<C-e>"
g.vimtex_compiler_method = "tectonic"
g.wiki_filetypes = {"md"}
g.wiki_link_target_type = "md"
g.wiki_map_link_create = function(txt) return txt:lower():gsub("%s+", "-") end
g.wiki_root = "~/Documents/wiki"
