font_family DankMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0
disable_ligatures never

window_margin_width 5
hide_window_decorations yes

# Nerd Fonts v2.3.3
symbol_map U+e738,U+e256,U+db82,U+df37,U+2615,U+279c,U+2718,U+21e1,U+2638,U+25ac  Symbols Nerd Font Mono
# Nerd Fonts v2.3.3
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

cursor_blink_interval 0

enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
bell_on_tab no

enabled_layouts Tall, *

shell /bin/zsh
shell_args -lc 'tmux a || tmux'
shell_integration enabled

detect_urls yes
url_style curly
confirm_os_window_close 0

term xterm-256color
macos_option_as_alt yes
