vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = 'none' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = 'none', fg = 'none' })
vim.api.nvim_set_hl(0, 'NonText', { bg = 'none' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = 'none' })
vim.api.nvim_set_hl(0, 'Structure', { bg = 'none' })
vim.api.nvim_set_hl(0, 'LineNr', { bg = 'none', italic = true, fg = '#777777' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = 'none', bold = true })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = 'none', bold = true })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = 'none', bold = true })
vim.api.nvim_set_hl(
  0,
  'Comment',
  { bg = 'none', fg = '#777777', italic = true }
)
vim.api.nvim_set_hl(0, 'Keyword', { italic = true })
vim.api.nvim_set_hl(0, 'Identifier', { italic = true })
vim.api.nvim_set_hl(0, 'StorageClass', { italic = true })
vim.api.nvim_set_hl(0, 'jsLineComment', { italic = true })
vim.api.nvim_set_hl(0, 'xmlAttrib', { italic = true })
vim.api.nvim_set_hl(0, 'htmlArg', { italic = true })
vim.api.nvim_set_hl(0, 'pythonSelf', { italic = true })
vim.api.nvim_set_hl(0, 'CmpItemKindCopilot', { italic = true })
vim.api.nvim_set_hl(0, 'CmpItemKindCopilot', { fg = '#6CC644' })
