require 'config.plugins.tokyonight'
require 'config.plugins.nvim-tree'
require 'config.plugins.autopairs'
require 'config.plugins.cmp'
require 'config.plugins.telescope'
require 'config.plugins.indentline'
require 'config.plugins.gitsign'
require 'config.plugins.lsp'
require 'config.plugins.galaxyline'
require 'config.plugins.comment'
require 'config.plugins.toggleterm'
require 'config.plugins.neogit'
require 'config.plugins.spectre'
require 'config.plugins.cmake'
-- require 'config.plugins.trouble'
-- require 'config.plugins.go'
