require "kr.plugins"
require "kr.settings"
require "kr.mappings"
require "kr.settings"
-- require "kr.commands"
require "kr.colors"
require "kr.autocmds"
require "kr.fold"
require "kr.filetree"
require "kr.lualine"
require "kr.treesitter"
require "kr.formatting"
require "kr.lsp"
