;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

(package! catppuccin-theme)
(package! solarized-theme)
(package! git-link)
(package! dash)
(package! jq-mode)
(package! move-text)
(package! ripgrep)
(package! format-sql)
(package! tldr)
(package! all-the-icons)
(package! ob-tmux)
(package! sqlup-mode)
(package! sqlformat)
(package! ejc-sql)
(package! lsp-tailwindcss :recipe (:host github :repo "merrickluo/lsp-tailwindcss"))
(package! go-eldoc)
(package! rainbow-delimiters)
(package! wakatime-mode)
(package! prism)
;; devdocs (port of devdocs.nvim)
(package! devdocs)
;; ufo-like folding (port of nvim-ufo)
(package! origami)
(package! lsp-origami)
(package! org-superstar)
