-- require 'config.plugins.synthwave'
require 'config.plugins.autopairs'
require 'config.plugins.cmp'
require 'config.plugins.comment'
require 'config.plugins.dap'
require 'config.plugins.galaxyline'
require 'config.plugins.gitsign'
require 'config.plugins.glow'
require 'config.plugins.indentline'
require 'config.plugins.lsp'
-- require 'config.plugins.neogit'
-- require 'config.plugins.nvim-tree'
-- require 'config.plugins.project'
-- require 'config.plugins.spectre'
require 'config.plugins.telescope'
require 'config.plugins.toggleterm'
-- require 'config.plugins.catpuccin'
require 'config.plugins.cmake'
require 'config.plugins.neotree'
require 'config.plugins.colorscheme'
-- require 'config.plugins.heirline'
