require(".plugins.config.alpha")
require(".plugins.config.cmp")
require(".plugins.config.lsp")
require(".plugins.config.lualine")
require(".plugins.config.outline")
require(".plugins.config.telescope")
require(".plugins.config.treesitter")
require(".plugins.config.whichkey")
require(".plugins.config.outline")
require(".plugins.config.nvimtree")
-- require('.plugins.config.formatter')
