# basic settings
set -g escape-time 10         # zero-out escape time delay
set -g history-limit 1000000 # increase history size (from 2,000)
set -g base-index 1          # start indexing windows at 1 instead of 0
setw -g pane-base-index 1
set -g mouse on              # enable mouse support
set -g display-time 750
set -g focus-events on

# terminal settings
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-256color:RGB"
set -g allow-passthrough on

# session settings
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g set-clipboard on      # use system clipboard
set -g clock-mode-style 24

# window settings
set -g renumber-windows on   # renumber all windows when any window is closed
setw -g automatic-rename on
set -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

# environment settings
set -g set-titles on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# vim: set ft=tmux :
