# vi mode
set -g status-keys vi
setw -g mode-keys vi

# remap default prefix
set -g prefix C-a
bind-key C-a send-prefix

# splitting
unbind %
unbind '"'
bind | split-window -c '#{pane_current_path}' -h
bind - split-window -c '#{pane_current_path}' -v

# panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key x kill-pane
bind-key X kill-window
bind-key q kill-session
bind-key Q kill-server

# resize panes with uppercase keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# vim mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key x kill-pane
# TODO: until I understand what this is
# bind-key e send-keys "tmux capture-pane -p -S - | nvim -c 'set buftype=nofile' +" Enter

bind-key "s" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t 🪟 ^g ⚙️ ^x 📁 ^d tmux kill ^f 🔎' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\"" 

# bind-key "s" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# break pane into a window
bind = select-layout even-vertical
bind + select-layout even-horizontal
# bind - break-pane
bind _ join-pane

bind t new-window -n ' ' -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
bind g new-window -c "#{pane_current_path}" -n "" "lazygit 2> /dev/null"
bind S new-window "k9s 2> /dev/null"


# reloading config
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded config"

# vim: set ft=tmux :
