# tpm plugin
set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'tmux-plugins/tmux-sensible'

# fzf
set -g @plugin "joshmedeski/tmux-fzf-url"
set -g @plugin 'sainnhe/tmux-fzf'
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'

# float
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'o'
set -g @floax-change-path 'true'

# set -g @tmux-last-color on
# set -g @tmux-last-pager 'less -r'
# set -g @tmux-last-pager 'less'
# set -g @tmux-last-prompt-pattern ' '
# nerd fonts
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"

set -g @tmux-nerd-font-window-name-shell-icon ''
set -g @tmux-nerd-font-window-name-show-name false


# plugins config

# pomodoro
set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_on " "
set -g @pomodoro_notifications 'on'
# set -g @pomodoro_granularity 'on'
