set -g status-style bg=default
set -g status-position top
set -g status-interval 10     # update the status bar every 10 seconds
set -g status-left-length 200    # increase length (from 10)
set -g status-right-length 200   # increase length (from 10)

set -g status-right "#[fg=white,nobold]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml) #[fg=yellow,bg=default]%d %b #[fg=white,bg=default]%H:%M #{pomodoro_status}"

# set -g message-command-style 'bg=default,fg=yellow'
# set -g message-style 'bg=default,fg=yellow'
# set -g mode-style 'bg=default,fg=yellow'
# set -g pane-active-border-style 'fg=white,bg=default'
# set -g pane-border-style 'fg=brightblack,bg=default'

# vim: set ft=tmux :
