local null = require("null-ls")

local formatters = {
	"stylua",
	"eslint_d",
	"prettier",
	"deno_fmt",
	"dart-format",
	"erlfmt",
	"fixjson",
	"gofmpt",
	"goimports",
	"golines",
	"mix",
	"prismafmt",
	"taplo",
}

null.setup({
	sources = {
		null.builtins.formatting.prettier,
		null.builtins.formatting.stylua,
		null.builtins.formatting.eslint_d,
		null.builtins.formatting.deno_fmt,
		null.builtins.formatting.dart_format,
		null.builtins.formatting.erlfmt,
		null.builtins.formatting.fixjson,
		null.builtins.formatting.gofmt,
		null.builtins.formatting.goimports,
		null.builtins.formatting.golines,
		null.builtins.formatting.taplo,
		null.builtins.formatting.mix,
		null.builtins.formatting.prismafmt,
		null.builtins.formatting.trim_whitespace,
		null.builtins.diagnostics.write_good,
		null.builtins.diagnostics.credo,
		null.builtins.diagnostics.eslint_d,
		null.builtins.diagnostics.hadolint,
		null.builtins.diagnostics.yamllint,
		null.builtins.diagnostics.revive,
		null.builtins.diagnostics.tsc,
		null.builtins.diagnostics.eslint_d,
		--null.builtins.diagnostics.luacheck,
		null.builtins.code_actions.gitsigns,
		null.builtins.code_actions.refactoring,
		null.builtins.completion.spell,
		null.builtins.completion.luasnip,
	},
})
